const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const Store={get(k,f=null){try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))},remove(k){localStorage.removeItem(k)}};
function initData(){if(!Store.get('products'))Store.set('products',INITIAL_PRODUCTS);if(!Store.get('categories'))Store.set('categories',INITIAL_CATEGORIES);if(!Store.get('toppings'))Store.set('toppings',INITIAL_TOPPINGS);if(!Store.get('promos'))Store.set('promos',INITIAL_PROMOS);if(!Store.get('orders'))Store.set('orders',[]);if(!Store.get('settings'))Store.set('settings',{...CAFE_CONFIG});}
const fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg,type='success'){let x=$('#toast');if(!x){x=document.createElement('div');x.id='toast';document.body.append(x)}x.textContent=msg;x.className=`toast show ${type}`;setTimeout(()=>x.className='toast',2600)}
function getCart(){return Store.get('cart',[])} function saveCart(c){Store.set('cart',c);updateCartBadge()}
function updateCartBadge(){const n=getCart().reduce((a,x)=>a+x.quantity,0);$$('[data-cart-count]').forEach(e=>e.textContent=n)}
function productCard(p){return `<article class="product-card"><a href="product.html?id=${p.id}" class="product-image"><img loading="lazy" src="${p.image}" alt="${esc(p.name)}">${p.stock<=0?'<span class="badge danger">OUT OF STOCK</span>':p.featured?'<span class="badge">FEATURED</span>':''}</a><div class="product-body"><div class="muted">${esc(p.category)}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="product-row"><strong>${fmt(p.price)}</strong><span>★ ${p.rating}</span></div><button class="btn primary full" data-add="${p.id}" ${p.stock<=0?'disabled':''}>Tambah</button></div></article>`}
function setupGlobal(){initData();if(!document.querySelector('#theme-toggle')){const b=document.createElement('button');b.id='theme-toggle';b.className='theme-toggle';b.title='Ubah tema';b.textContent='Tema';document.body.appendChild(b);b.onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';Store.set('theme',n);applyTheme(n)}}document.documentElement.style.setProperty('--primary',Store.get('settings',CAFE_CONFIG).PRIMARY_COLOR||CAFE_CONFIG.PRIMARY_COLOR);const s=Store.get('settings',CAFE_CONFIG);$$('[data-cafe-name]').forEach(e=>e.textContent=s.CAFE_NAME);$$('[data-cafe-tagline]').forEach(e=>e.textContent=s.CAFE_TAGLINE);$$('[data-cafe-address]').forEach(e=>e.textContent=s.CAFE_ADDRESS);$$('[data-cafe-wa]').forEach(e=>e.href=`https://wa.me/${s.CAFE_WHATSAPP}`);updateCartBadge();$$('[data-theme]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.theme;Store.set('theme',v);applyTheme(v)}));applyTheme(Store.get('theme','system'));const nav=$('.hamburger'),menu=$('.nav-links');if(nav)nav.addEventListener('click',()=>menu.classList.toggle('open'));document.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b)addToCart(b.dataset.add)});}
function applyTheme(v){const dark=v==='dark'||(v==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
function addToCart(id,opts={}){const p=Store.get('products',[]).find(x=>x.id===id);if(!p||p.stock<=0)return toast('Produk sedang habis','error');const variant=opts.variant||p.variants[1];const toppings=opts.toppings||[];const price=variant.price+toppings.reduce((a,t)=>a+t.price,0);const key=[id,variant.name,toppings.map(t=>t.id).sort().join(','),opts.sugar||'50%',opts.ice||'Normal',opts.note||''].join('|');const c=getCart(),found=c.find(x=>x.key===key);if(found)found.quantity+=opts.quantity||1;else c.push({key,productId:id,product:p,variant:variant.name,basePrice:variant.price,toppings,sugar:opts.sugar||'50%',ice:opts.ice||'Normal',note:opts.note||'',quantity:opts.quantity||1,price});saveCart(c);toast('Produk berhasil ditambahkan ke keranjang.')}
function calcTotals(cart=getCart(),promo=null){const subtotal=cart.reduce((a,x)=>a+x.price*x.quantity,0);let discount=0;if(promo&&subtotal>=promo.minPurchase){discount=promo.type==='percentage'?Math.min(subtotal*promo.value/100,promo.maxDiscount||Infinity):Math.min(promo.value,promo.maxDiscount||Infinity)}const s=Store.get('settings',CAFE_CONFIG),tax=Math.max(0,(subtotal-discount))*(Number(s.TAX_RATE)||0),service=Number(s.SERVICE_FEE)||0,delivery=Number(s.DELIVERY_FEE)||0;return{subtotal,discount,tax,serviceFee:service,deliveryFee:delivery,total:Math.max(0,subtotal-discount+tax+service+delivery)}}
function orderNumber(){const d=new Date(),ds=d.toISOString().slice(0,10).replaceAll('-',''),orders=Store.get('orders',[]);return `CAF-${ds}-${String(orders.length+1).padStart(4,'0')}`}
setupGlobal();
